const express = require('express');
const router = express.Router();
const authController = require('../controllers/authController');
const userController = require('../controllers/userController');
const exam = require('../controllers/examController');
const student = require('../controllers/studentController');
const teacher = require('../controllers/teacherController');
const subscription = require('../controllers/subscriptionController');
const organization = require('../controllers/organizationController');
const teacherRequests = require('../controllers/teacherRequestController');
const rankings = require('../controllers/rankingController');
const batch = require('../controllers/batchController');
const service = require('../controllers/serviceController');
const adminRoutes = require('./adminRoutes');
const { auth, allowRoles, requireActiveTeacherAccess } = require('../middleware/auth');
const { requireFields } = require('../middleware/validate');
const csvUpload = require('../middleware/csvUpload');

router.post('/auth/register', requireFields('name','email','password','role'), authController.register);
router.post('/auth/login', requireFields('email','password'), authController.login);
router.post('/auth/logout', auth, authController.logout);
router.get('/auth/me', auth, authController.me);
router.post('/v1/auth/register', requireFields('name','email','password','role'), authController.register);
router.post('/v1/auth/login', requireFields('email','password'), authController.login);
router.post('/v1/auth/logout', auth, authController.logout);
router.get('/v1/auth/me', auth, authController.me);
router.get('/users/me', auth, authController.me);
router.patch('/users/me', auth, userController.updateMe);
router.post('/users/me/avatar', auth, express.raw({ type: ['image/jpeg','image/png','image/webp'], limit: '2mb' }), userController.uploadAvatar);
router.get('/organizations/me', auth, organization.me);
router.patch('/organizations/me', auth, allowRoles('organization_owner'), organization.updateMe);
router.post('/organizations/me/logo', auth, allowRoles('organization_owner'), express.raw({ type: ['image/jpeg','image/png','image/webp'], limit: '3mb' }), organization.uploadLogo);
router.post('/organizations/me/verification', auth, allowRoles('organization_owner'), express.raw({ type: ['application/pdf','application/x-pdf'], limit: '10mb' }), organization.submitVerification);
router.get('/organizations/dashboard-summary', auth, allowRoles('organization_owner'), organization.dashboardSummary);
router.get('/organizations/students', auth, allowRoles('organization_owner','teacher'), requireActiveTeacherAccess, organization.students);
router.get('/organizations/students/:studentId', auth, allowRoles('organization_owner','teacher'), requireActiveTeacherAccess, organization.studentDetails);
router.get('/organizations/teachers', auth, allowRoles('organization_owner'), organization.teachers);
router.get('/organizations/teachers/:teacherId', auth, allowRoles('organization_owner'), organization.teacherDetails);
router.patch('/organizations/teachers/:teacherId/assign', auth, allowRoles('organization_owner'), organization.assignTeacher);
router.patch('/organizations/teachers/:teacherId/pause', auth, allowRoles('organization_owner'), organization.pauseTeacher);
router.patch('/organizations/teachers/:teacherId/reactivate', auth, allowRoles('organization_owner'), organization.reactivateTeacher);
router.patch('/organizations/teachers/:teacherId/remove', auth, allowRoles('organization_owner'), organization.removeTeacher);
router.delete('/organizations/teachers/:teacherId/remove', auth, allowRoles('organization_owner'), organization.removeTeacher);
router.post('/organizations/join-by-code', auth, allowRoles('student'), organization.joinByCode);
router.patch('/organizations/leave', auth, allowRoles('student'), organization.leave);
router.post('/teacher-requests/join-organization', auth, allowRoles('teacher'), teacherRequests.joinOrganization);
router.get('/teacher-requests/organization', auth, allowRoles('organization_owner'), teacherRequests.organizationRequests);
router.patch('/teacher-requests/:id/accept', auth, allowRoles('organization_owner'), teacherRequests.review('accepted'));
router.patch('/teacher-requests/:id/reject', auth, allowRoles('organization_owner'), teacherRequests.review('rejected'));
router.post('/users/invite', auth, allowRoles('organization_owner'), requireFields('email','role'), userController.invite);
router.use('/admin', auth, allowRoles('super_admin'), adminRoutes);
router.use('/v1/admin', auth, allowRoles('super_admin'), adminRoutes);

const staff = [auth, allowRoles('organization_owner','teacher'), requireActiveTeacherAccess];
router.post('/services', ...staff, requireFields('name'), service.create);
router.get('/services', ...staff, service.list);
router.get('/services/:id', ...staff, service.get);
router.patch('/services/:id', ...staff, service.update);
router.delete('/services/:id', ...staff, service.remove);
router.post('/exam-slots', ...staff, requireFields('title','category','examType','startDateTime','durationMinutes'), exam.createSlot);
router.get('/organization/students', ...staff, organization.students);
router.post('/batches', ...staff, batch.create);
router.get('/batches', auth, batch.list);
router.post('/batches/join-by-code', auth, allowRoles('student'), batch.joinByCode);
router.patch('/batches/:id/leave', auth, allowRoles('student'), batch.leave);
router.get('/batches/:id', ...staff, batch.get);
router.get('/batches/:id/exam-slots', ...staff, batch.examSlots);
router.patch('/batches/:id', ...staff, batch.update);
router.patch('/batches/:id/deactivate', ...staff, batch.deactivate);
router.delete('/batches/:id', ...staff, batch.remove);
router.get('/exam-slots', ...staff, exam.listManaged);
router.get('/exam-slots/access-options', ...staff, exam.accessOptions);
router.get('/exam-slots/question-import/sample/true-false-csv', ...staff, exam.sampleCsv('trueFalse'));
router.get('/exam-slots/question-import/sample/single-best-csv', ...staff, exam.sampleCsv('singleBest'));
router.get('/exam-slots/:id', ...staff, exam.getManaged);
router.patch('/exam-slots/:id', ...staff, exam.updateSlot);
router.delete('/exam-slots/:id', ...staff, exam.deleteSlot);
router.post('/exam-slots/:id/questions', ...staff, requireFields('type','questionText','marks'), exam.addQuestion);
router.get('/exam-slots/:id/questions', ...staff, exam.listQuestions);
router.post('/exam-slots/:id/questions/import/true-false-csv', ...staff, csvUpload, exam.importQuestions('trueFalse'));
router.post('/exam-slots/:id/questions/import/single-best-csv', ...staff, csvUpload, exam.importQuestions('singleBest'));
router.get('/questions/:questionId', ...staff, exam.getQuestion);
router.patch('/questions/:questionId', ...staff, requireFields('type','questionText','marks'), exam.updateQuestion);
router.delete('/questions/:questionId', ...staff, exam.deleteQuestion);
router.post('/exam-slots/:id/assign-students', ...staff, exam.assign);
router.post('/exam-slots/:id/remove-student', ...staff, requireFields('studentId'), exam.removeStudent);
router.get('/teacher/access-requests', ...staff, teacher.requests);
router.patch('/teacher/access-requests/:id/accept', ...staff, teacher.reviewRequest('accepted'));
router.patch('/teacher/access-requests/:id/reject', ...staff, teacher.reviewRequest('rejected'));
router.get('/exam-slots/:id/submissions', ...staff, teacher.submissions);
router.get('/submissions/:id', ...staff, teacher.submission);
router.patch('/submissions/:id/review-written', ...staff, teacher.reviewWritten);
router.patch('/exam-slots/:id/publish-results', ...staff, exam.publishResults);

const students = [auth, allowRoles('student')];
router.get('/student/exam-slots', ...students, student.listSlots);
router.post('/student/exam-slots/:id/request-access', ...students, student.requestAccess);
router.get('/student/exam-slots/:id', ...students, student.getExam);
router.post('/student/exam-slots/:id/submit', ...students, student.submit);
router.get('/student/results', ...students, student.results);
router.get('/student/results/:submissionId', ...students, student.resultDetail);
router.get('/student/activity', ...students, student.activity);
router.get('/teacher/activity', ...staff, teacher.activity);
router.get('/teacher/history', ...staff, teacher.history);
router.get('/teacher/dashboard-summary', ...staff, teacher.dashboardSummary);
router.get('/rankings/organization', auth, rankings.organization);
router.get('/rankings/service/:serviceId', auth, rankings.service);
router.get('/rankings/batch/:batchId', auth, rankings.batch);
router.get('/student/my-ranking', ...students, rankings.myRanking);
router.get('/plans', auth, subscription.plans);
router.get('/v1/plans', auth, subscription.plans);
router.get('/subscriptions/me', auth, allowRoles('organization_owner'), subscription.current);
router.get('/v1/subscriptions/me', auth, allowRoles('organization_owner'), subscription.current);
router.post('/subscriptions/upgrade-request', auth, allowRoles('organization_owner'), subscription.upgradeRequest);
router.post('/v1/subscriptions/upgrade-request', auth, allowRoles('organization_owner'), subscription.upgradeRequest);
router.get('/subscription/current', auth, subscription.current);
module.exports = router;
